/* wixl.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __WIXL_H__
#define __WIXL_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libmsi.h>
#include <libxml/tree.h>
#include <libcommon.h>
#include <gio/gio.h>

G_BEGIN_DECLS


#define WIXL_TYPE_MSI_DEFAULT (wixl_msi_default_get_type ())
#define WIXL_MSI_DEFAULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_MSI_DEFAULT, WixlMSIDefault))
#define WIXL_MSI_DEFAULT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_MSI_DEFAULT, WixlMSIDefaultClass))
#define WIXL_IS_MSI_DEFAULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_MSI_DEFAULT))
#define WIXL_IS_MSI_DEFAULT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_MSI_DEFAULT))
#define WIXL_MSI_DEFAULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_MSI_DEFAULT, WixlMSIDefaultClass))

typedef struct _WixlMSIDefault WixlMSIDefault;
typedef struct _WixlMSIDefaultClass WixlMSIDefaultClass;
typedef struct _WixlMSIDefaultPrivate WixlMSIDefaultPrivate;

#define WIXL_MSI_DEFAULT_TYPE_ACTION_FLAGS (wixl_msi_default_action_flags_get_type ())

#define WIXL_MSI_DEFAULT_TYPE_ACTION (wixl_msi_default_action_get_type ())

#define WIXL_MSI_DEFAULT_TYPE_ACTION_INFO (wixl_msi_default_action_info_get_type ())
typedef struct _WixlMSIDefaultActionInfo WixlMSIDefaultActionInfo;

#define WIXL_TYPE_MSI_TABLE (wixl_msi_table_get_type ())
#define WIXL_MSI_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_MSI_TABLE, WixlMsiTable))
#define WIXL_MSI_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_MSI_TABLE, WixlMsiTableClass))
#define WIXL_IS_MSI_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_MSI_TABLE))
#define WIXL_IS_MSI_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_MSI_TABLE))
#define WIXL_MSI_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_MSI_TABLE, WixlMsiTableClass))

typedef struct _WixlMsiTable WixlMsiTable;
typedef struct _WixlMsiTableClass WixlMsiTableClass;
typedef struct _WixlMsiTablePrivate WixlMsiTablePrivate;

#define WIXL_TYPE_MSI_TABLE_SEQUENCE (wixl_msi_table_sequence_get_type ())
#define WIXL_MSI_TABLE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_MSI_TABLE_SEQUENCE, WixlMsiTableSequence))
#define WIXL_MSI_TABLE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_MSI_TABLE_SEQUENCE, WixlMsiTableSequenceClass))
#define WIXL_IS_MSI_TABLE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_MSI_TABLE_SEQUENCE))
#define WIXL_IS_MSI_TABLE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_MSI_TABLE_SEQUENCE))
#define WIXL_MSI_TABLE_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_MSI_TABLE_SEQUENCE, WixlMsiTableSequenceClass))

typedef struct _WixlMsiTableSequence WixlMsiTableSequence;
typedef struct _WixlMsiTableSequenceClass WixlMsiTableSequenceClass;
typedef struct _WixlMsiTableSequencePrivate WixlMsiTableSequencePrivate;

#define WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION (wixl_msi_table_sequence_action_get_type ())
#define WIXL_MSI_TABLE_SEQUENCE_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION, WixlMsiTableSequenceAction))
#define WIXL_MSI_TABLE_SEQUENCE_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION, WixlMsiTableSequenceActionClass))
#define WIXL_MSI_TABLE_SEQUENCE_IS_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION))
#define WIXL_MSI_TABLE_SEQUENCE_IS_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION))
#define WIXL_MSI_TABLE_SEQUENCE_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_MSI_TABLE_SEQUENCE_TYPE_ACTION, WixlMsiTableSequenceActionClass))

typedef struct _WixlMsiTableSequenceAction WixlMsiTableSequenceAction;
typedef struct _WixlMsiTableSequenceActionClass WixlMsiTableSequenceActionClass;
typedef struct _WixlMsiTableSequenceActionPrivate WixlMsiTableSequenceActionPrivate;

#define WIXL_TYPE_WIX_NODE (wixl_wix_node_get_type ())
#define WIXL_WIX_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_NODE, WixlWixNode))
#define WIXL_WIX_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_NODE, WixlWixNodeClass))
#define WIXL_IS_WIX_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_NODE))
#define WIXL_IS_WIX_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_NODE))
#define WIXL_WIX_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_NODE, WixlWixNodeClass))

typedef struct _WixlWixNode WixlWixNode;
typedef struct _WixlWixNodeClass WixlWixNodeClass;

#define WIXL_TYPE_WIX_ELEMENT (wixl_wix_element_get_type ())
#define WIXL_WIX_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ELEMENT, WixlWixElement))
#define WIXL_WIX_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ELEMENT, WixlWixElementClass))
#define WIXL_IS_WIX_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ELEMENT))
#define WIXL_IS_WIX_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ELEMENT))
#define WIXL_WIX_ELEMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ELEMENT, WixlWixElementClass))

typedef struct _WixlWixElement WixlWixElement;
typedef struct _WixlWixElementClass WixlWixElementClass;

#define WIXL_TYPE_WIX_ACTION (wixl_wix_action_get_type ())
#define WIXL_WIX_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ACTION, WixlWixAction))
#define WIXL_WIX_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ACTION, WixlWixActionClass))
#define WIXL_IS_WIX_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ACTION))
#define WIXL_IS_WIX_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ACTION))
#define WIXL_WIX_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ACTION, WixlWixActionClass))

typedef struct _WixlWixAction WixlWixAction;
typedef struct _WixlWixActionClass WixlWixActionClass;

#define WIXL_TYPE_WIX_RESOLVER (wixl_wix_resolver_get_type ())
#define WIXL_WIX_RESOLVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_RESOLVER, WixlWixResolver))
#define WIXL_IS_WIX_RESOLVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_RESOLVER))
#define WIXL_WIX_RESOLVER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), WIXL_TYPE_WIX_RESOLVER, WixlWixResolverIface))

typedef struct _WixlWixResolver WixlWixResolver;
typedef struct _WixlWixResolverIface WixlWixResolverIface;

#define WIXL_TYPE_VISIT_STATE (wixl_visit_state_get_type ())

#define WIXL_TYPE_WIX_NODE_VISITOR (wixl_wix_node_visitor_get_type ())
#define WIXL_WIX_NODE_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_NODE_VISITOR, WixlWixNodeVisitor))
#define WIXL_WIX_NODE_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_NODE_VISITOR, WixlWixNodeVisitorClass))
#define WIXL_IS_WIX_NODE_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_NODE_VISITOR))
#define WIXL_IS_WIX_NODE_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_NODE_VISITOR))
#define WIXL_WIX_NODE_VISITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_NODE_VISITOR, WixlWixNodeVisitorClass))

typedef struct _WixlWixNodeVisitor WixlWixNodeVisitor;
typedef struct _WixlWixNodeVisitorClass WixlWixNodeVisitorClass;
typedef struct _WixlWixNodeVisitorPrivate WixlWixNodeVisitorPrivate;

#define WIXL_TYPE_WIX_PRODUCT (wixl_wix_product_get_type ())
#define WIXL_WIX_PRODUCT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_PRODUCT, WixlWixProduct))
#define WIXL_WIX_PRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_PRODUCT, WixlWixProductClass))
#define WIXL_IS_WIX_PRODUCT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_PRODUCT))
#define WIXL_IS_WIX_PRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_PRODUCT))
#define WIXL_WIX_PRODUCT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_PRODUCT, WixlWixProductClass))

typedef struct _WixlWixProduct WixlWixProduct;
typedef struct _WixlWixProductClass WixlWixProductClass;

#define WIXL_TYPE_WIX_ICON (wixl_wix_icon_get_type ())
#define WIXL_WIX_ICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ICON, WixlWixIcon))
#define WIXL_WIX_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ICON, WixlWixIconClass))
#define WIXL_IS_WIX_ICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ICON))
#define WIXL_IS_WIX_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ICON))
#define WIXL_WIX_ICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ICON, WixlWixIconClass))

typedef struct _WixlWixIcon WixlWixIcon;
typedef struct _WixlWixIconClass WixlWixIconClass;

#define WIXL_TYPE_WIX_PACKAGE (wixl_wix_package_get_type ())
#define WIXL_WIX_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_PACKAGE, WixlWixPackage))
#define WIXL_WIX_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_PACKAGE, WixlWixPackageClass))
#define WIXL_IS_WIX_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_PACKAGE))
#define WIXL_IS_WIX_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_PACKAGE))
#define WIXL_WIX_PACKAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_PACKAGE, WixlWixPackageClass))

typedef struct _WixlWixPackage WixlWixPackage;
typedef struct _WixlWixPackageClass WixlWixPackageClass;

#define WIXL_TYPE_WIX_PROPERTY (wixl_wix_property_get_type ())
#define WIXL_WIX_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_PROPERTY, WixlWixProperty))
#define WIXL_WIX_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_PROPERTY, WixlWixPropertyClass))
#define WIXL_IS_WIX_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_PROPERTY))
#define WIXL_IS_WIX_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_PROPERTY))
#define WIXL_WIX_PROPERTY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_PROPERTY, WixlWixPropertyClass))

typedef struct _WixlWixProperty WixlWixProperty;
typedef struct _WixlWixPropertyClass WixlWixPropertyClass;

#define WIXL_TYPE_WIX_MEDIA (wixl_wix_media_get_type ())
#define WIXL_WIX_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_MEDIA, WixlWixMedia))
#define WIXL_WIX_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_MEDIA, WixlWixMediaClass))
#define WIXL_IS_WIX_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_MEDIA))
#define WIXL_IS_WIX_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_MEDIA))
#define WIXL_WIX_MEDIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_MEDIA, WixlWixMediaClass))

typedef struct _WixlWixMedia WixlWixMedia;
typedef struct _WixlWixMediaClass WixlWixMediaClass;

#define WIXL_TYPE_WIX_DIRECTORY (wixl_wix_directory_get_type ())
#define WIXL_WIX_DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_DIRECTORY, WixlWixDirectory))
#define WIXL_WIX_DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_DIRECTORY, WixlWixDirectoryClass))
#define WIXL_IS_WIX_DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_DIRECTORY))
#define WIXL_IS_WIX_DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_DIRECTORY))
#define WIXL_WIX_DIRECTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_DIRECTORY, WixlWixDirectoryClass))

typedef struct _WixlWixDirectory WixlWixDirectory;
typedef struct _WixlWixDirectoryClass WixlWixDirectoryClass;

#define WIXL_TYPE_WIX_COMPONENT (wixl_wix_component_get_type ())
#define WIXL_WIX_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_COMPONENT, WixlWixComponent))
#define WIXL_WIX_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_COMPONENT, WixlWixComponentClass))
#define WIXL_IS_WIX_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_COMPONENT))
#define WIXL_IS_WIX_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_COMPONENT))
#define WIXL_WIX_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_COMPONENT, WixlWixComponentClass))

typedef struct _WixlWixComponent WixlWixComponent;
typedef struct _WixlWixComponentClass WixlWixComponentClass;

#define WIXL_TYPE_WIX_FEATURE (wixl_wix_feature_get_type ())
#define WIXL_WIX_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_FEATURE, WixlWixFeature))
#define WIXL_WIX_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_FEATURE, WixlWixFeatureClass))
#define WIXL_IS_WIX_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_FEATURE))
#define WIXL_IS_WIX_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_FEATURE))
#define WIXL_WIX_FEATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_FEATURE, WixlWixFeatureClass))

typedef struct _WixlWixFeature WixlWixFeature;
typedef struct _WixlWixFeatureClass WixlWixFeatureClass;

#define WIXL_TYPE_WIX_ELEMENT_REF (wixl_wix_element_ref_get_type ())
#define WIXL_WIX_ELEMENT_REF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ELEMENT_REF, WixlWixElementRef))
#define WIXL_WIX_ELEMENT_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ELEMENT_REF, WixlWixElementRefClass))
#define WIXL_IS_WIX_ELEMENT_REF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ELEMENT_REF))
#define WIXL_IS_WIX_ELEMENT_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ELEMENT_REF))
#define WIXL_WIX_ELEMENT_REF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ELEMENT_REF, WixlWixElementRefClass))

typedef struct _WixlWixElementRef WixlWixElementRef;
typedef struct _WixlWixElementRefClass WixlWixElementRefClass;

#define WIXL_TYPE_WIX_COMPONENT_REF (wixl_wix_component_ref_get_type ())
#define WIXL_WIX_COMPONENT_REF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_COMPONENT_REF, WixlWixComponentRef))
#define WIXL_WIX_COMPONENT_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_COMPONENT_REF, WixlWixComponentRefClass))
#define WIXL_IS_WIX_COMPONENT_REF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_COMPONENT_REF))
#define WIXL_IS_WIX_COMPONENT_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_COMPONENT_REF))
#define WIXL_WIX_COMPONENT_REF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_COMPONENT_REF, WixlWixComponentRefClass))

typedef struct _WixlWixComponentRef WixlWixComponentRef;
typedef struct _WixlWixComponentRefClass WixlWixComponentRefClass;

#define WIXL_TYPE_WIX_REMOVE_FOLDER (wixl_wix_remove_folder_get_type ())
#define WIXL_WIX_REMOVE_FOLDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_REMOVE_FOLDER, WixlWixRemoveFolder))
#define WIXL_WIX_REMOVE_FOLDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_REMOVE_FOLDER, WixlWixRemoveFolderClass))
#define WIXL_IS_WIX_REMOVE_FOLDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_REMOVE_FOLDER))
#define WIXL_IS_WIX_REMOVE_FOLDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_REMOVE_FOLDER))
#define WIXL_WIX_REMOVE_FOLDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_REMOVE_FOLDER, WixlWixRemoveFolderClass))

typedef struct _WixlWixRemoveFolder WixlWixRemoveFolder;
typedef struct _WixlWixRemoveFolderClass WixlWixRemoveFolderClass;

#define WIXL_TYPE_WIX_KEY_ELEMENT (wixl_wix_key_element_get_type ())
#define WIXL_WIX_KEY_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_KEY_ELEMENT, WixlWixKeyElement))
#define WIXL_WIX_KEY_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_KEY_ELEMENT, WixlWixKeyElementClass))
#define WIXL_IS_WIX_KEY_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_KEY_ELEMENT))
#define WIXL_IS_WIX_KEY_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_KEY_ELEMENT))
#define WIXL_WIX_KEY_ELEMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_KEY_ELEMENT, WixlWixKeyElementClass))

typedef struct _WixlWixKeyElement WixlWixKeyElement;
typedef struct _WixlWixKeyElementClass WixlWixKeyElementClass;

#define WIXL_TYPE_WIX_REGISTRY_VALUE (wixl_wix_registry_value_get_type ())
#define WIXL_WIX_REGISTRY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_REGISTRY_VALUE, WixlWixRegistryValue))
#define WIXL_WIX_REGISTRY_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_REGISTRY_VALUE, WixlWixRegistryValueClass))
#define WIXL_IS_WIX_REGISTRY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_REGISTRY_VALUE))
#define WIXL_IS_WIX_REGISTRY_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_REGISTRY_VALUE))
#define WIXL_WIX_REGISTRY_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_REGISTRY_VALUE, WixlWixRegistryValueClass))

typedef struct _WixlWixRegistryValue WixlWixRegistryValue;
typedef struct _WixlWixRegistryValueClass WixlWixRegistryValueClass;

#define WIXL_TYPE_WIX_FILE (wixl_wix_file_get_type ())
#define WIXL_WIX_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_FILE, WixlWixFile))
#define WIXL_WIX_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_FILE, WixlWixFileClass))
#define WIXL_IS_WIX_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_FILE))
#define WIXL_IS_WIX_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_FILE))
#define WIXL_WIX_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_FILE, WixlWixFileClass))

typedef struct _WixlWixFile WixlWixFile;
typedef struct _WixlWixFileClass WixlWixFileClass;

#define WIXL_TYPE_WIX_SHORTCUT (wixl_wix_shortcut_get_type ())
#define WIXL_WIX_SHORTCUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SHORTCUT, WixlWixShortcut))
#define WIXL_WIX_SHORTCUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SHORTCUT, WixlWixShortcutClass))
#define WIXL_IS_WIX_SHORTCUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SHORTCUT))
#define WIXL_IS_WIX_SHORTCUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SHORTCUT))
#define WIXL_WIX_SHORTCUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SHORTCUT, WixlWixShortcutClass))

typedef struct _WixlWixShortcut WixlWixShortcut;
typedef struct _WixlWixShortcutClass WixlWixShortcutClass;

#define WIXL_TYPE_WIX_CREATE_FOLDER (wixl_wix_create_folder_get_type ())
#define WIXL_WIX_CREATE_FOLDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_CREATE_FOLDER, WixlWixCreateFolder))
#define WIXL_WIX_CREATE_FOLDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_CREATE_FOLDER, WixlWixCreateFolderClass))
#define WIXL_IS_WIX_CREATE_FOLDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_CREATE_FOLDER))
#define WIXL_IS_WIX_CREATE_FOLDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_CREATE_FOLDER))
#define WIXL_WIX_CREATE_FOLDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_CREATE_FOLDER, WixlWixCreateFolderClass))

typedef struct _WixlWixCreateFolder WixlWixCreateFolder;
typedef struct _WixlWixCreateFolderClass WixlWixCreateFolderClass;

#define WIXL_TYPE_WIX_FRAGMENT (wixl_wix_fragment_get_type ())
#define WIXL_WIX_FRAGMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_FRAGMENT, WixlWixFragment))
#define WIXL_WIX_FRAGMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_FRAGMENT, WixlWixFragmentClass))
#define WIXL_IS_WIX_FRAGMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_FRAGMENT))
#define WIXL_IS_WIX_FRAGMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_FRAGMENT))
#define WIXL_WIX_FRAGMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_FRAGMENT, WixlWixFragmentClass))

typedef struct _WixlWixFragment WixlWixFragment;
typedef struct _WixlWixFragmentClass WixlWixFragmentClass;

#define WIXL_TYPE_WIX_SEQUENCE (wixl_wix_sequence_get_type ())
#define WIXL_WIX_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SEQUENCE, WixlWixSequence))
#define WIXL_WIX_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SEQUENCE, WixlWixSequenceClass))
#define WIXL_IS_WIX_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SEQUENCE))
#define WIXL_IS_WIX_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SEQUENCE))
#define WIXL_WIX_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SEQUENCE, WixlWixSequenceClass))

typedef struct _WixlWixSequence WixlWixSequence;
typedef struct _WixlWixSequenceClass WixlWixSequenceClass;

#define WIXL_TYPE_WIX_CONDITION (wixl_wix_condition_get_type ())
#define WIXL_WIX_CONDITION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_CONDITION, WixlWixCondition))
#define WIXL_WIX_CONDITION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_CONDITION, WixlWixConditionClass))
#define WIXL_IS_WIX_CONDITION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_CONDITION))
#define WIXL_IS_WIX_CONDITION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_CONDITION))
#define WIXL_WIX_CONDITION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_CONDITION, WixlWixConditionClass))

typedef struct _WixlWixCondition WixlWixCondition;
typedef struct _WixlWixConditionClass WixlWixConditionClass;

#define WIXL_TYPE_WIX_UPGRADE (wixl_wix_upgrade_get_type ())
#define WIXL_WIX_UPGRADE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_UPGRADE, WixlWixUpgrade))
#define WIXL_WIX_UPGRADE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_UPGRADE, WixlWixUpgradeClass))
#define WIXL_IS_WIX_UPGRADE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_UPGRADE))
#define WIXL_IS_WIX_UPGRADE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_UPGRADE))
#define WIXL_WIX_UPGRADE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_UPGRADE, WixlWixUpgradeClass))

typedef struct _WixlWixUpgrade WixlWixUpgrade;
typedef struct _WixlWixUpgradeClass WixlWixUpgradeClass;

#define WIXL_TYPE_WIX_UPGRADE_VERSION (wixl_wix_upgrade_version_get_type ())
#define WIXL_WIX_UPGRADE_VERSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_UPGRADE_VERSION, WixlWixUpgradeVersion))
#define WIXL_WIX_UPGRADE_VERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_UPGRADE_VERSION, WixlWixUpgradeVersionClass))
#define WIXL_IS_WIX_UPGRADE_VERSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_UPGRADE_VERSION))
#define WIXL_IS_WIX_UPGRADE_VERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_UPGRADE_VERSION))
#define WIXL_WIX_UPGRADE_VERSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_UPGRADE_VERSION, WixlWixUpgradeVersionClass))

typedef struct _WixlWixUpgradeVersion WixlWixUpgradeVersion;
typedef struct _WixlWixUpgradeVersionClass WixlWixUpgradeVersionClass;

#define WIXL_TYPE_WIX_TEXT (wixl_wix_text_get_type ())
#define WIXL_WIX_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_TEXT, WixlWixText))
#define WIXL_WIX_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_TEXT, WixlWixTextClass))
#define WIXL_IS_WIX_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_TEXT))
#define WIXL_IS_WIX_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_TEXT))
#define WIXL_WIX_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_TEXT, WixlWixTextClass))

typedef struct _WixlWixText WixlWixText;
typedef struct _WixlWixTextClass WixlWixTextClass;

#define WIXL_TYPE_WIX_COMPONENT_GROUP_REF (wixl_wix_component_group_ref_get_type ())
#define WIXL_WIX_COMPONENT_GROUP_REF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP_REF, WixlWixComponentGroupRef))
#define WIXL_WIX_COMPONENT_GROUP_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_COMPONENT_GROUP_REF, WixlWixComponentGroupRefClass))
#define WIXL_IS_WIX_COMPONENT_GROUP_REF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP_REF))
#define WIXL_IS_WIX_COMPONENT_GROUP_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_COMPONENT_GROUP_REF))
#define WIXL_WIX_COMPONENT_GROUP_REF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP_REF, WixlWixComponentGroupRefClass))

typedef struct _WixlWixComponentGroupRef WixlWixComponentGroupRef;
typedef struct _WixlWixComponentGroupRefClass WixlWixComponentGroupRefClass;

#define WIXL_TYPE_WIX_PROG_ID (wixl_wix_prog_id_get_type ())
#define WIXL_WIX_PROG_ID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_PROG_ID, WixlWixProgId))
#define WIXL_WIX_PROG_ID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_PROG_ID, WixlWixProgIdClass))
#define WIXL_IS_WIX_PROG_ID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_PROG_ID))
#define WIXL_IS_WIX_PROG_ID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_PROG_ID))
#define WIXL_WIX_PROG_ID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_PROG_ID, WixlWixProgIdClass))

typedef struct _WixlWixProgId WixlWixProgId;
typedef struct _WixlWixProgIdClass WixlWixProgIdClass;

#define WIXL_TYPE_WIX_EXTENSION (wixl_wix_extension_get_type ())
#define WIXL_WIX_EXTENSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_EXTENSION, WixlWixExtension))
#define WIXL_WIX_EXTENSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_EXTENSION, WixlWixExtensionClass))
#define WIXL_IS_WIX_EXTENSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_EXTENSION))
#define WIXL_IS_WIX_EXTENSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_EXTENSION))
#define WIXL_WIX_EXTENSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_EXTENSION, WixlWixExtensionClass))

typedef struct _WixlWixExtension WixlWixExtension;
typedef struct _WixlWixExtensionClass WixlWixExtensionClass;

#define WIXL_TYPE_WIX_VERB (wixl_wix_verb_get_type ())
#define WIXL_WIX_VERB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_VERB, WixlWixVerb))
#define WIXL_WIX_VERB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_VERB, WixlWixVerbClass))
#define WIXL_IS_WIX_VERB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_VERB))
#define WIXL_IS_WIX_VERB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_VERB))
#define WIXL_WIX_VERB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_VERB, WixlWixVerbClass))

typedef struct _WixlWixVerb WixlWixVerb;
typedef struct _WixlWixVerbClass WixlWixVerbClass;

#define WIXL_TYPE_WIX_MIME (wixl_wix_mime_get_type ())
#define WIXL_WIX_MIME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_MIME, WixlWixMIME))
#define WIXL_WIX_MIME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_MIME, WixlWixMIMEClass))
#define WIXL_IS_WIX_MIME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_MIME))
#define WIXL_IS_WIX_MIME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_MIME))
#define WIXL_WIX_MIME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_MIME, WixlWixMIMEClass))

typedef struct _WixlWixMIME WixlWixMIME;
typedef struct _WixlWixMIMEClass WixlWixMIMEClass;

#define WIXL_TYPE_WIX_SERVICE_ARGUMENT (wixl_wix_service_argument_get_type ())
#define WIXL_WIX_SERVICE_ARGUMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SERVICE_ARGUMENT, WixlWixServiceArgument))
#define WIXL_WIX_SERVICE_ARGUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SERVICE_ARGUMENT, WixlWixServiceArgumentClass))
#define WIXL_IS_WIX_SERVICE_ARGUMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SERVICE_ARGUMENT))
#define WIXL_IS_WIX_SERVICE_ARGUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SERVICE_ARGUMENT))
#define WIXL_WIX_SERVICE_ARGUMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SERVICE_ARGUMENT, WixlWixServiceArgumentClass))

typedef struct _WixlWixServiceArgument WixlWixServiceArgument;
typedef struct _WixlWixServiceArgumentClass WixlWixServiceArgumentClass;

#define WIXL_TYPE_WIX_SERVICE_CONTROL (wixl_wix_service_control_get_type ())
#define WIXL_WIX_SERVICE_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SERVICE_CONTROL, WixlWixServiceControl))
#define WIXL_WIX_SERVICE_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SERVICE_CONTROL, WixlWixServiceControlClass))
#define WIXL_IS_WIX_SERVICE_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SERVICE_CONTROL))
#define WIXL_IS_WIX_SERVICE_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SERVICE_CONTROL))
#define WIXL_WIX_SERVICE_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SERVICE_CONTROL, WixlWixServiceControlClass))

typedef struct _WixlWixServiceControl WixlWixServiceControl;
typedef struct _WixlWixServiceControlClass WixlWixServiceControlClass;

#define WIXL_TYPE_WIX_SERVICE_DEPENDENCY (wixl_wix_service_dependency_get_type ())
#define WIXL_WIX_SERVICE_DEPENDENCY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SERVICE_DEPENDENCY, WixlWixServiceDependency))
#define WIXL_WIX_SERVICE_DEPENDENCY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SERVICE_DEPENDENCY, WixlWixServiceDependencyClass))
#define WIXL_IS_WIX_SERVICE_DEPENDENCY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SERVICE_DEPENDENCY))
#define WIXL_IS_WIX_SERVICE_DEPENDENCY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SERVICE_DEPENDENCY))
#define WIXL_WIX_SERVICE_DEPENDENCY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SERVICE_DEPENDENCY, WixlWixServiceDependencyClass))

typedef struct _WixlWixServiceDependency WixlWixServiceDependency;
typedef struct _WixlWixServiceDependencyClass WixlWixServiceDependencyClass;

#define WIXL_TYPE_WIX_SERVICE_INSTALL (wixl_wix_service_install_get_type ())
#define WIXL_WIX_SERVICE_INSTALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_SERVICE_INSTALL, WixlWixServiceInstall))
#define WIXL_WIX_SERVICE_INSTALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_SERVICE_INSTALL, WixlWixServiceInstallClass))
#define WIXL_IS_WIX_SERVICE_INSTALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_SERVICE_INSTALL))
#define WIXL_IS_WIX_SERVICE_INSTALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_SERVICE_INSTALL))
#define WIXL_WIX_SERVICE_INSTALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_SERVICE_INSTALL, WixlWixServiceInstallClass))

typedef struct _WixlWixServiceInstall WixlWixServiceInstall;
typedef struct _WixlWixServiceInstallClass WixlWixServiceInstallClass;

#define WIXL_TYPE_WIX_REGISTRY_SEARCH (wixl_wix_registry_search_get_type ())
#define WIXL_WIX_REGISTRY_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_REGISTRY_SEARCH, WixlWixRegistrySearch))
#define WIXL_WIX_REGISTRY_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_REGISTRY_SEARCH, WixlWixRegistrySearchClass))
#define WIXL_IS_WIX_REGISTRY_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_REGISTRY_SEARCH))
#define WIXL_IS_WIX_REGISTRY_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_REGISTRY_SEARCH))
#define WIXL_WIX_REGISTRY_SEARCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_REGISTRY_SEARCH, WixlWixRegistrySearchClass))

typedef struct _WixlWixRegistrySearch WixlWixRegistrySearch;
typedef struct _WixlWixRegistrySearchClass WixlWixRegistrySearchClass;

#define WIXL_TYPE_WIX_CUSTOM_ACTION (wixl_wix_custom_action_get_type ())
#define WIXL_WIX_CUSTOM_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_CUSTOM_ACTION, WixlWixCustomAction))
#define WIXL_WIX_CUSTOM_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_CUSTOM_ACTION, WixlWixCustomActionClass))
#define WIXL_IS_WIX_CUSTOM_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_CUSTOM_ACTION))
#define WIXL_IS_WIX_CUSTOM_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_CUSTOM_ACTION))
#define WIXL_WIX_CUSTOM_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_CUSTOM_ACTION, WixlWixCustomActionClass))

typedef struct _WixlWixCustomAction WixlWixCustomAction;
typedef struct _WixlWixCustomActionClass WixlWixCustomActionClass;

#define WIXL_TYPE_WIX_BINARY (wixl_wix_binary_get_type ())
#define WIXL_WIX_BINARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_BINARY, WixlWixBinary))
#define WIXL_WIX_BINARY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_BINARY, WixlWixBinaryClass))
#define WIXL_IS_WIX_BINARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_BINARY))
#define WIXL_IS_WIX_BINARY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_BINARY))
#define WIXL_WIX_BINARY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_BINARY, WixlWixBinaryClass))

typedef struct _WixlWixBinary WixlWixBinary;
typedef struct _WixlWixBinaryClass WixlWixBinaryClass;

#define WIXL_TYPE_WIX_MAJOR_UPGRADE (wixl_wix_major_upgrade_get_type ())
#define WIXL_WIX_MAJOR_UPGRADE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_MAJOR_UPGRADE, WixlWixMajorUpgrade))
#define WIXL_WIX_MAJOR_UPGRADE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_MAJOR_UPGRADE, WixlWixMajorUpgradeClass))
#define WIXL_IS_WIX_MAJOR_UPGRADE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_MAJOR_UPGRADE))
#define WIXL_IS_WIX_MAJOR_UPGRADE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_MAJOR_UPGRADE))
#define WIXL_WIX_MAJOR_UPGRADE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_MAJOR_UPGRADE, WixlWixMajorUpgradeClass))

typedef struct _WixlWixMajorUpgrade WixlWixMajorUpgrade;
typedef struct _WixlWixMajorUpgradeClass WixlWixMajorUpgradeClass;

#define WIXL_TYPE_WIX_MEDIA_TEMPLATE (wixl_wix_media_template_get_type ())
#define WIXL_WIX_MEDIA_TEMPLATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_MEDIA_TEMPLATE, WixlWixMediaTemplate))
#define WIXL_WIX_MEDIA_TEMPLATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_MEDIA_TEMPLATE, WixlWixMediaTemplateClass))
#define WIXL_IS_WIX_MEDIA_TEMPLATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_MEDIA_TEMPLATE))
#define WIXL_IS_WIX_MEDIA_TEMPLATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_MEDIA_TEMPLATE))
#define WIXL_WIX_MEDIA_TEMPLATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_MEDIA_TEMPLATE, WixlWixMediaTemplateClass))

typedef struct _WixlWixMediaTemplate WixlWixMediaTemplate;
typedef struct _WixlWixMediaTemplateClass WixlWixMediaTemplateClass;
typedef struct _WixlWixNodePrivate WixlWixNodePrivate;
typedef struct _WixlWixTextPrivate WixlWixTextPrivate;
typedef struct _WixlWixElementPrivate WixlWixElementPrivate;

#define WIXL_TYPE_WIX_COMPONENT_GROUP (wixl_wix_component_group_get_type ())
#define WIXL_WIX_COMPONENT_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP, WixlWixComponentGroup))
#define WIXL_WIX_COMPONENT_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_COMPONENT_GROUP, WixlWixComponentGroupClass))
#define WIXL_IS_WIX_COMPONENT_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP))
#define WIXL_IS_WIX_COMPONENT_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_COMPONENT_GROUP))
#define WIXL_WIX_COMPONENT_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_COMPONENT_GROUP, WixlWixComponentGroupClass))

typedef struct _WixlWixComponentGroup WixlWixComponentGroup;
typedef struct _WixlWixComponentGroupClass WixlWixComponentGroupClass;
typedef struct _WixlWixComponentGroupPrivate WixlWixComponentGroupPrivate;
typedef struct _WixlWixFragmentPrivate WixlWixFragmentPrivate;
typedef struct _WixlWixRegistrySearchPrivate WixlWixRegistrySearchPrivate;
typedef struct _WixlWixPropertyPrivate WixlWixPropertyPrivate;
typedef struct _WixlWixPackagePrivate WixlWixPackagePrivate;
typedef struct _WixlWixCreateFolderPrivate WixlWixCreateFolderPrivate;
typedef struct _WixlWixIconPrivate WixlWixIconPrivate;
typedef struct _WixlWixShortcutPrivate WixlWixShortcutPrivate;
typedef struct _WixlWixKeyElementPrivate WixlWixKeyElementPrivate;
typedef struct _WixlWixFilePrivate WixlWixFilePrivate;
typedef struct _WixlWixRegistryValuePrivate WixlWixRegistryValuePrivate;
typedef struct _WixlWixRemoveFolderPrivate WixlWixRemoveFolderPrivate;
typedef struct _WixlWixFeaturePrivate WixlWixFeaturePrivate;
typedef struct _WixlWixElementRefPrivate WixlWixElementRefPrivate;
typedef struct _WixlWixComponentRefPrivate WixlWixComponentRefPrivate;
typedef struct _WixlWixComponentGroupRefPrivate WixlWixComponentGroupRefPrivate;
typedef struct _WixlWixConditionPrivate WixlWixConditionPrivate;
typedef struct _WixlWixMIMEPrivate WixlWixMIMEPrivate;
typedef struct _WixlWixServiceArgumentPrivate WixlWixServiceArgumentPrivate;
typedef struct _WixlWixServiceControlPrivate WixlWixServiceControlPrivate;
typedef struct _WixlWixServiceDependencyPrivate WixlWixServiceDependencyPrivate;
typedef struct _WixlWixServiceInstallPrivate WixlWixServiceInstallPrivate;
typedef struct _WixlWixVerbPrivate WixlWixVerbPrivate;
typedef struct _WixlWixExtensionPrivate WixlWixExtensionPrivate;
typedef struct _WixlWixProgIdPrivate WixlWixProgIdPrivate;
typedef struct _WixlWixActionPrivate WixlWixActionPrivate;
typedef struct _WixlWixSequencePrivate WixlWixSequencePrivate;

#define WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE (wixl_wix_install_execute_sequence_get_type ())
#define WIXL_WIX_INSTALL_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE, WixlWixInstallExecuteSequence))
#define WIXL_WIX_INSTALL_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE, WixlWixInstallExecuteSequenceClass))
#define WIXL_IS_WIX_INSTALL_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE))
#define WIXL_IS_WIX_INSTALL_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE))
#define WIXL_WIX_INSTALL_EXECUTE_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_INSTALL_EXECUTE_SEQUENCE, WixlWixInstallExecuteSequenceClass))

typedef struct _WixlWixInstallExecuteSequence WixlWixInstallExecuteSequence;
typedef struct _WixlWixInstallExecuteSequenceClass WixlWixInstallExecuteSequenceClass;
typedef struct _WixlWixInstallExecuteSequencePrivate WixlWixInstallExecuteSequencePrivate;

#define WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE (wixl_wix_install_ui_sequence_get_type ())
#define WIXL_WIX_INSTALL_UI_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE, WixlWixInstallUISequence))
#define WIXL_WIX_INSTALL_UI_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE, WixlWixInstallUISequenceClass))
#define WIXL_IS_WIX_INSTALL_UI_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE))
#define WIXL_IS_WIX_INSTALL_UI_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE))
#define WIXL_WIX_INSTALL_UI_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_INSTALL_UI_SEQUENCE, WixlWixInstallUISequenceClass))

typedef struct _WixlWixInstallUISequence WixlWixInstallUISequence;
typedef struct _WixlWixInstallUISequenceClass WixlWixInstallUISequenceClass;
typedef struct _WixlWixInstallUISequencePrivate WixlWixInstallUISequencePrivate;

#define WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE (wixl_wix_admin_execute_sequence_get_type ())
#define WIXL_WIX_ADMIN_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE, WixlWixAdminExecuteSequence))
#define WIXL_WIX_ADMIN_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE, WixlWixAdminExecuteSequenceClass))
#define WIXL_IS_WIX_ADMIN_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE))
#define WIXL_IS_WIX_ADMIN_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE))
#define WIXL_WIX_ADMIN_EXECUTE_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ADMIN_EXECUTE_SEQUENCE, WixlWixAdminExecuteSequenceClass))

typedef struct _WixlWixAdminExecuteSequence WixlWixAdminExecuteSequence;
typedef struct _WixlWixAdminExecuteSequenceClass WixlWixAdminExecuteSequenceClass;
typedef struct _WixlWixAdminExecuteSequencePrivate WixlWixAdminExecuteSequencePrivate;

#define WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE (wixl_wix_admin_ui_sequence_get_type ())
#define WIXL_WIX_ADMIN_UI_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE, WixlWixAdminUISequence))
#define WIXL_WIX_ADMIN_UI_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE, WixlWixAdminUISequenceClass))
#define WIXL_IS_WIX_ADMIN_UI_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE))
#define WIXL_IS_WIX_ADMIN_UI_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE))
#define WIXL_WIX_ADMIN_UI_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ADMIN_UI_SEQUENCE, WixlWixAdminUISequenceClass))

typedef struct _WixlWixAdminUISequence WixlWixAdminUISequence;
typedef struct _WixlWixAdminUISequenceClass WixlWixAdminUISequenceClass;
typedef struct _WixlWixAdminUISequencePrivate WixlWixAdminUISequencePrivate;

#define WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE (wixl_wix_advertise_execute_sequence_get_type ())
#define WIXL_WIX_ADVERTISE_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE, WixlWixAdvertiseExecuteSequence))
#define WIXL_WIX_ADVERTISE_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE, WixlWixAdvertiseExecuteSequenceClass))
#define WIXL_IS_WIX_ADVERTISE_EXECUTE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE))
#define WIXL_IS_WIX_ADVERTISE_EXECUTE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE))
#define WIXL_WIX_ADVERTISE_EXECUTE_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_ADVERTISE_EXECUTE_SEQUENCE, WixlWixAdvertiseExecuteSequenceClass))

typedef struct _WixlWixAdvertiseExecuteSequence WixlWixAdvertiseExecuteSequence;
typedef struct _WixlWixAdvertiseExecuteSequenceClass WixlWixAdvertiseExecuteSequenceClass;
typedef struct _WixlWixAdvertiseExecuteSequencePrivate WixlWixAdvertiseExecuteSequencePrivate;
typedef struct _WixlWixUpgradePrivate WixlWixUpgradePrivate;
typedef struct _WixlWixUpgradeVersionPrivate WixlWixUpgradeVersionPrivate;
typedef struct _WixlWixCustomActionPrivate WixlWixCustomActionPrivate;
typedef struct _WixlWixBinaryPrivate WixlWixBinaryPrivate;
typedef struct _WixlWixMajorUpgradePrivate WixlWixMajorUpgradePrivate;
typedef struct _WixlWixMediaTemplatePrivate WixlWixMediaTemplatePrivate;
typedef struct _WixlWixProductPrivate WixlWixProductPrivate;
typedef struct _WixlWixMediaPrivate WixlWixMediaPrivate;

#define WIXL_TYPE_WIX_REGISTRY_KEY (wixl_wix_registry_key_get_type ())
#define WIXL_WIX_REGISTRY_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_REGISTRY_KEY, WixlWixRegistryKey))
#define WIXL_WIX_REGISTRY_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_REGISTRY_KEY, WixlWixRegistryKeyClass))
#define WIXL_IS_WIX_REGISTRY_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_REGISTRY_KEY))
#define WIXL_IS_WIX_REGISTRY_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_REGISTRY_KEY))
#define WIXL_WIX_REGISTRY_KEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_REGISTRY_KEY, WixlWixRegistryKeyClass))

typedef struct _WixlWixRegistryKey WixlWixRegistryKey;
typedef struct _WixlWixRegistryKeyClass WixlWixRegistryKeyClass;
typedef struct _WixlWixRegistryKeyPrivate WixlWixRegistryKeyPrivate;
typedef struct _WixlWixComponentPrivate WixlWixComponentPrivate;
typedef struct _WixlWixDirectoryPrivate WixlWixDirectoryPrivate;

#define WIXL_TYPE_WIX_DIRECTORY_REF (wixl_wix_directory_ref_get_type ())
#define WIXL_WIX_DIRECTORY_REF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIXL_TYPE_WIX_DIRECTORY_REF, WixlWixDirectoryRef))
#define WIXL_WIX_DIRECTORY_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIXL_TYPE_WIX_DIRECTORY_REF, WixlWixDirectoryRefClass))
#define WIXL_IS_WIX_DIRECTORY_REF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIXL_TYPE_WIX_DIRECTORY_REF))
#define WIXL_IS_WIX_DIRECTORY_REF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIXL_TYPE_WIX_DIRECTORY_REF))
#define WIXL_WIX_DIRECTORY_REF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIXL_TYPE_WIX_DIRECTORY_REF, WixlWixDirectoryRefClass))

typedef struct _WixlWixDirectoryRef WixlWixDirectoryRef;
typedef struct _WixlWixDirectoryRefClass WixlWixDirectoryRefClass;
typedef struct _WixlWixDirectoryRefPrivate WixlWixDirectoryRefPrivate;

struct _WixlMSIDefault {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WixlMSIDefaultPrivate * priv;
};

struct _WixlMSIDefaultClass {
	GTypeClass parent_class;
	void (*finalize) (WixlMSIDefault *self);
};

typedef enum  {
	WIXL_MSI_DEFAULT_ACTION_FLAGS_ADMIN_EXECUTE_SEQUENCE = 1 << 0,
	WIXL_MSI_DEFAULT_ACTION_FLAGS_ADMIN_UI_SEQUENCE = 1 << 1,
	WIXL_MSI_DEFAULT_ACTION_FLAGS_ADVT_EXECUTE_SEQUENCE = 1 << 2,
	WIXL_MSI_DEFAULT_ACTION_FLAGS_INSTALL_EXECUTE_SEQUENCE = 1 << 3,
	WIXL_MSI_DEFAULT_ACTION_FLAGS_INSTALL_UI_SEQUENCE = 1 << 4,
	WIXL_MSI_DEFAULT_ACTION_FLAGS_ALL = -1
} WixlMSIDefaultActionFlags;

typedef enum  {
	WIXL_MSI_DEFAULT_ACTION_InstallInitialize,
	WIXL_MSI_DEFAULT_ACTION_InstallExecute,
	WIXL_MSI_DEFAULT_ACTION_InstallExecuteAgain,
	WIXL_MSI_DEFAULT_ACTION_InstallFinalize,
	WIXL_MSI_DEFAULT_ACTION_InstallFiles,
	WIXL_MSI_DEFAULT_ACTION_InstallAdminPackage,
	WIXL_MSI_DEFAULT_ACTION_FileCost,
	WIXL_MSI_DEFAULT_ACTION_CostInitialize,
	WIXL_MSI_DEFAULT_ACTION_CostFinalize,
	WIXL_MSI_DEFAULT_ACTION_InstallValidate,
	WIXL_MSI_DEFAULT_ACTION_ExecuteAction,
	WIXL_MSI_DEFAULT_ACTION_CreateShortcuts,
	WIXL_MSI_DEFAULT_ACTION_MsiPublishAssemblies,
	WIXL_MSI_DEFAULT_ACTION_PublishComponents,
	WIXL_MSI_DEFAULT_ACTION_PublishFeatures,
	WIXL_MSI_DEFAULT_ACTION_PublishProduct,
	WIXL_MSI_DEFAULT_ACTION_RegisterClassInfo,
	WIXL_MSI_DEFAULT_ACTION_RegisterExtensionInfo,
	WIXL_MSI_DEFAULT_ACTION_RegisterMIMEInfo,
	WIXL_MSI_DEFAULT_ACTION_RegisterProgIdInfo,
	WIXL_MSI_DEFAULT_ACTION_AllocateRegistrySpace,
	WIXL_MSI_DEFAULT_ACTION_AppSearch,
	WIXL_MSI_DEFAULT_ACTION_BindImage,
	WIXL_MSI_DEFAULT_ACTION_CCPSearch,
	WIXL_MSI_DEFAULT_ACTION_CreateFolders,
	WIXL_MSI_DEFAULT_ACTION_DeleteServices,
	WIXL_MSI_DEFAULT_ACTION_DuplicateFiles,
	WIXL_MSI_DEFAULT_ACTION_FindRelatedProducts,
	WIXL_MSI_DEFAULT_ACTION_InstallODBC,
	WIXL_MSI_DEFAULT_ACTION_InstallServices,
	WIXL_MSI_DEFAULT_ACTION_MsiConfigureServices,
	WIXL_MSI_DEFAULT_ACTION_IsolateComponents,
	WIXL_MSI_DEFAULT_ACTION_LaunchConditions,
	WIXL_MSI_DEFAULT_ACTION_MigrateFeatureStates,
	WIXL_MSI_DEFAULT_ACTION_MoveFiles,
	WIXL_MSI_DEFAULT_ACTION_PatchFiles,
	WIXL_MSI_DEFAULT_ACTION_ProcessComponents,
	WIXL_MSI_DEFAULT_ACTION_RegisterComPlus,
	WIXL_MSI_DEFAULT_ACTION_RegisterFonts,
	WIXL_MSI_DEFAULT_ACTION_RegisterProduct,
	WIXL_MSI_DEFAULT_ACTION_RegisterTypeLibraries,
	WIXL_MSI_DEFAULT_ACTION_RegisterUser,
	WIXL_MSI_DEFAULT_ACTION_RemoveDuplicateFiles,
	WIXL_MSI_DEFAULT_ACTION_RemoveEnvironmentStrings,
	WIXL_MSI_DEFAULT_ACTION_RemoveFiles,
	WIXL_MSI_DEFAULT_ACTION_RemoveFolders,
	WIXL_MSI_DEFAULT_ACTION_RemoveIniValues,
	WIXL_MSI_DEFAULT_ACTION_RemoveODBC,
	WIXL_MSI_DEFAULT_ACTION_RemoveRegistryValues,
	WIXL_MSI_DEFAULT_ACTION_RemoveShortcuts,
	WIXL_MSI_DEFAULT_ACTION_RMCCPSearch,
	WIXL_MSI_DEFAULT_ACTION_SelfRegModules,
	WIXL_MSI_DEFAULT_ACTION_SelfUnregModules,
	WIXL_MSI_DEFAULT_ACTION_SetODBCFolders,
	WIXL_MSI_DEFAULT_ACTION_StartServices,
	WIXL_MSI_DEFAULT_ACTION_StopServices,
	WIXL_MSI_DEFAULT_ACTION_MsiUnpublishAssemblies,
	WIXL_MSI_DEFAULT_ACTION_UnpublishComponents,
	WIXL_MSI_DEFAULT_ACTION_UnpublishFeatures,
	WIXL_MSI_DEFAULT_ACTION_UnregisterClassInfo,
	WIXL_MSI_DEFAULT_ACTION_UnregisterComPlus,
	WIXL_MSI_DEFAULT_ACTION_UnregisterExtensionInfo,
	WIXL_MSI_DEFAULT_ACTION_UnregisterFonts,
	WIXL_MSI_DEFAULT_ACTION_UnregisterMIMEInfo,
	WIXL_MSI_DEFAULT_ACTION_UnregisterProgIdInfo,
	WIXL_MSI_DEFAULT_ACTION_UnregisterTypeLibraries,
	WIXL_MSI_DEFAULT_ACTION_ValidateProductID,
	WIXL_MSI_DEFAULT_ACTION_WriteEnvironmentStrings,
	WIXL_MSI_DEFAULT_ACTION_WriteIniValues,
	WIXL_MSI_DEFAULT_ACTION_WriteRegistryValues
} WixlMSIDefaultAction;

struct _WixlMSIDefaultActionInfo {
	gchar* name;
	gchar* condition;
	gint sequence;
	WixlMSIDefaultActionFlags flags;
};

struct _WixlMsiTable {
	GObject parent_instance;
	WixlMsiTablePrivate * priv;
	GList* records;
};

struct _WixlMsiTableClass {
	GObjectClass parent_class;
	void (*create) (WixlMsiTable* self, LibmsiDatabase* db, GError** error);
	gchar* name;
	gchar* sql_create;
	gchar* sql_insert;
};

struct _WixlMsiTableSequence {
	WixlMsiTable parent_instance;
	WixlMsiTableSequencePrivate * priv;
};

struct _WixlMsiTableSequenceClass {
	WixlMsiTableClass parent_class;
	WixlMSIDefaultActionFlags flags;
};

struct _WixlMsiTableSequenceAction {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WixlMsiTableSequenceActionPrivate * priv;
	gchar* name;
	gchar* condition;
	gint sequence;
	WixlWixAction* action;
	gboolean visited;
	gboolean incoming_deps;
	GHashTable* depends_on;
};

struct _WixlMsiTableSequenceActionClass {
	GTypeClass parent_class;
	void (*finalize) (WixlMsiTableSequenceAction *self);
};

struct _WixlWixResolverIface {
	GTypeInterface parent_iface;
	gpointer (*find_element) (WixlWixResolver* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, const gchar* Id);
};

typedef enum  {
	WIXL_VISIT_STATE_ENTER,
	WIXL_VISIT_STATE_INFIX,
	WIXL_VISIT_STATE_LEAVE
} WixlVisitState;

struct _WixlWixNodeVisitor {
	GObject parent_instance;
	WixlWixNodeVisitorPrivate * priv;
};

struct _WixlWixNodeVisitorClass {
	GObjectClass parent_class;
	void (*visit_product) (WixlWixNodeVisitor* self, WixlWixProduct* product, GError** error);
	void (*visit_icon) (WixlWixNodeVisitor* self, WixlWixIcon* icon, GError** error);
	void (*visit_package) (WixlWixNodeVisitor* self, WixlWixPackage* package, GError** error);
	void (*visit_property) (WixlWixNodeVisitor* self, WixlWixProperty* prop, GError** error);
	void (*visit_media) (WixlWixNodeVisitor* self, WixlWixMedia* media, GError** error);
	void (*visit_directory) (WixlWixNodeVisitor* self, WixlWixDirectory* dir, GError** error);
	void (*visit_component) (WixlWixNodeVisitor* self, WixlWixComponent* comp, WixlVisitState state, GError** error);
	void (*visit_feature) (WixlWixNodeVisitor* self, WixlWixFeature* feature, WixlVisitState state, GError** error);
	void (*visit_component_ref) (WixlWixNodeVisitor* self, WixlWixComponentRef* ref, GError** error);
	void (*visit_remove_folder) (WixlWixNodeVisitor* self, WixlWixRemoveFolder* rm, GError** error);
	void (*visit_registry_value) (WixlWixNodeVisitor* self, WixlWixRegistryValue* reg, GError** error);
	void (*visit_file) (WixlWixNodeVisitor* self, WixlWixFile* reg, GError** error);
	void (*visit_shortcut) (WixlWixNodeVisitor* self, WixlWixShortcut* shortcut, GError** error);
	void (*visit_create_folder) (WixlWixNodeVisitor* self, WixlWixCreateFolder* folder, GError** error);
	void (*visit_fragment) (WixlWixNodeVisitor* self, WixlWixFragment* fragment, GError** error);
	void (*visit_sequence) (WixlWixNodeVisitor* self, WixlWixSequence* sequence, GError** error);
	void (*visit_condition) (WixlWixNodeVisitor* self, WixlWixCondition* condition, GError** error);
	void (*visit_upgrade) (WixlWixNodeVisitor* self, WixlWixUpgrade* upgrade, GError** error);
	void (*visit_upgrade_version) (WixlWixNodeVisitor* self, WixlWixUpgradeVersion* version, GError** error);
	void (*visit_action) (WixlWixNodeVisitor* self, WixlWixAction* action, GError** error);
	void (*visit_text) (WixlWixNodeVisitor* self, WixlWixText* text, GError** error);
	void (*visit_component_group_ref) (WixlWixNodeVisitor* self, WixlWixComponentGroupRef* ref, GError** error);
	void (*visit_progid) (WixlWixNodeVisitor* self, WixlWixProgId* progid, GError** error);
	void (*visit_extension) (WixlWixNodeVisitor* self, WixlWixExtension* extension, GError** error);
	void (*visit_verb) (WixlWixNodeVisitor* self, WixlWixVerb* verb, GError** error);
	void (*visit_mime) (WixlWixNodeVisitor* self, WixlWixMIME* mime, GError** error);
	void (*visit_service_argument) (WixlWixNodeVisitor* self, WixlWixServiceArgument* service_argument, GError** error);
	void (*visit_service_control) (WixlWixNodeVisitor* self, WixlWixServiceControl* service_control, WixlVisitState state, GError** error);
	void (*visit_service_dependency) (WixlWixNodeVisitor* self, WixlWixServiceDependency* service_dependency, GError** error);
	void (*visit_service_install) (WixlWixNodeVisitor* self, WixlWixServiceInstall* service_install, WixlVisitState state, GError** error);
	void (*visit_registry_search) (WixlWixNodeVisitor* self, WixlWixRegistrySearch* search, GError** error);
	void (*visit_custom_action) (WixlWixNodeVisitor* self, WixlWixCustomAction* action, GError** error);
	void (*visit_binary) (WixlWixNodeVisitor* self, WixlWixBinary* binary, GError** error);
	void (*visit_major_upgrade) (WixlWixNodeVisitor* self, WixlWixMajorUpgrade* major, GError** error);
	void (*visit_media_template) (WixlWixNodeVisitor* self, WixlWixMediaTemplate* media, GError** error);
};

struct _WixlWixNode {
	GObject parent_instance;
	WixlWixNodePrivate * priv;
	WixlWixElement* parent;
};

struct _WixlWixNodeClass {
	GObjectClass parent_class;
	gchar* (*to_string) (WixlWixNode* self);
	void (*accept) (WixlWixNode* self, WixlWixNodeVisitor* visitor, GError** error);
};

struct _WixlWixText {
	WixlWixNode parent_instance;
	WixlWixTextPrivate * priv;
	gchar* Text;
};

struct _WixlWixTextClass {
	WixlWixNodeClass parent_class;
};

struct _WixlWixElement {
	WixlWixNode parent_instance;
	WixlWixElementPrivate * priv;
	GList* children;
};

struct _WixlWixElementClass {
	WixlWixNodeClass parent_class;
	gchar* (*full_path) (WixlWixElement* self, WixlWixResolver* r, GError** error);
	void (*load) (WixlWixElement* self, xmlNode* node, GError** error);
	gchar* name;
	GHashTable* child_types;
};

struct _WixlWixComponentGroup {
	WixlWixElement parent_instance;
	WixlWixComponentGroupPrivate * priv;
};

struct _WixlWixComponentGroupClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixFragment {
	WixlWixElement parent_instance;
	WixlWixFragmentPrivate * priv;
};

struct _WixlWixFragmentClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixRegistrySearch {
	WixlWixElement parent_instance;
	WixlWixRegistrySearchPrivate * priv;
};

struct _WixlWixRegistrySearchClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixProperty {
	WixlWixElement parent_instance;
	WixlWixPropertyPrivate * priv;
};

struct _WixlWixPropertyClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixPackage {
	WixlWixElement parent_instance;
	WixlWixPackagePrivate * priv;
};

struct _WixlWixPackageClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixCreateFolder {
	WixlWixElement parent_instance;
	WixlWixCreateFolderPrivate * priv;
};

struct _WixlWixCreateFolderClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixIcon {
	WixlWixElement parent_instance;
	WixlWixIconPrivate * priv;
	GFile* file;
};

struct _WixlWixIconClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixShortcut {
	WixlWixElement parent_instance;
	WixlWixShortcutPrivate * priv;
	LibmsiRecord* record;
};

struct _WixlWixShortcutClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixKeyElement {
	WixlWixElement parent_instance;
	WixlWixKeyElementPrivate * priv;
};

struct _WixlWixKeyElementClass {
	WixlWixElementClass parent_class;
	gchar* (*path_name) (WixlWixKeyElement* self, GError** error);
};

struct _WixlWixFile {
	WixlWixKeyElement parent_instance;
	WixlWixFilePrivate * priv;
	GFile* file;
};

struct _WixlWixFileClass {
	WixlWixKeyElementClass parent_class;
};

struct _WixlWixRegistryValue {
	WixlWixKeyElement parent_instance;
	WixlWixRegistryValuePrivate * priv;
};

struct _WixlWixRegistryValueClass {
	WixlWixKeyElementClass parent_class;
};

struct _WixlWixRemoveFolder {
	WixlWixElement parent_instance;
	WixlWixRemoveFolderPrivate * priv;
};

struct _WixlWixRemoveFolderClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixFeature {
	WixlWixElement parent_instance;
	WixlWixFeaturePrivate * priv;
};

struct _WixlWixFeatureClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixElementRef {
	WixlWixElement parent_instance;
	WixlWixElementRefPrivate * priv;
	gpointer resolved;
};

struct _WixlWixElementRefClass {
	WixlWixElementClass parent_class;
	GType ref_type;
};

struct _WixlWixComponentRef {
	WixlWixElementRef parent_instance;
	WixlWixComponentRefPrivate * priv;
};

struct _WixlWixComponentRefClass {
	WixlWixElementRefClass parent_class;
};

struct _WixlWixComponentGroupRef {
	WixlWixElementRef parent_instance;
	WixlWixComponentGroupRefPrivate * priv;
};

struct _WixlWixComponentGroupRefClass {
	WixlWixElementRefClass parent_class;
};

struct _WixlWixCondition {
	WixlWixElement parent_instance;
	WixlWixConditionPrivate * priv;
};

struct _WixlWixConditionClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixMIME {
	WixlWixElement parent_instance;
	WixlWixMIMEPrivate * priv;
};

struct _WixlWixMIMEClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixServiceArgument {
	WixlWixElement parent_instance;
	WixlWixServiceArgumentPrivate * priv;
};

struct _WixlWixServiceArgumentClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixServiceControl {
	WixlWixElement parent_instance;
	WixlWixServiceControlPrivate * priv;
};

struct _WixlWixServiceControlClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixServiceDependency {
	WixlWixElement parent_instance;
	WixlWixServiceDependencyPrivate * priv;
};

struct _WixlWixServiceDependencyClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixServiceInstall {
	WixlWixElement parent_instance;
	WixlWixServiceInstallPrivate * priv;
};

struct _WixlWixServiceInstallClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixVerb {
	WixlWixElement parent_instance;
	WixlWixVerbPrivate * priv;
};

struct _WixlWixVerbClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixExtension {
	WixlWixElement parent_instance;
	WixlWixExtensionPrivate * priv;
};

struct _WixlWixExtensionClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixProgId {
	WixlWixElement parent_instance;
	WixlWixProgIdPrivate * priv;
};

struct _WixlWixProgIdClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixAction {
	WixlWixElement parent_instance;
	WixlWixActionPrivate * priv;
	gchar* name;
};

struct _WixlWixActionClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixSequence {
	WixlWixElement parent_instance;
	WixlWixSequencePrivate * priv;
};

struct _WixlWixSequenceClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixInstallExecuteSequence {
	WixlWixSequence parent_instance;
	WixlWixInstallExecuteSequencePrivate * priv;
};

struct _WixlWixInstallExecuteSequenceClass {
	WixlWixSequenceClass parent_class;
};

struct _WixlWixInstallUISequence {
	WixlWixSequence parent_instance;
	WixlWixInstallUISequencePrivate * priv;
};

struct _WixlWixInstallUISequenceClass {
	WixlWixSequenceClass parent_class;
};

struct _WixlWixAdminExecuteSequence {
	WixlWixSequence parent_instance;
	WixlWixAdminExecuteSequencePrivate * priv;
};

struct _WixlWixAdminExecuteSequenceClass {
	WixlWixSequenceClass parent_class;
};

struct _WixlWixAdminUISequence {
	WixlWixSequence parent_instance;
	WixlWixAdminUISequencePrivate * priv;
};

struct _WixlWixAdminUISequenceClass {
	WixlWixSequenceClass parent_class;
};

struct _WixlWixAdvertiseExecuteSequence {
	WixlWixSequence parent_instance;
	WixlWixAdvertiseExecuteSequencePrivate * priv;
};

struct _WixlWixAdvertiseExecuteSequenceClass {
	WixlWixSequenceClass parent_class;
};

struct _WixlWixUpgrade {
	WixlWixElement parent_instance;
	WixlWixUpgradePrivate * priv;
};

struct _WixlWixUpgradeClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixUpgradeVersion {
	WixlWixElement parent_instance;
	WixlWixUpgradeVersionPrivate * priv;
};

struct _WixlWixUpgradeVersionClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixCustomAction {
	WixlWixElement parent_instance;
	WixlWixCustomActionPrivate * priv;
};

struct _WixlWixCustomActionClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixBinary {
	WixlWixElement parent_instance;
	WixlWixBinaryPrivate * priv;
	GFile* file;
};

struct _WixlWixBinaryClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixMajorUpgrade {
	WixlWixElement parent_instance;
	WixlWixMajorUpgradePrivate * priv;
};

struct _WixlWixMajorUpgradeClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixMediaTemplate {
	WixlWixElement parent_instance;
	WixlWixMediaTemplatePrivate * priv;
};

struct _WixlWixMediaTemplateClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixProduct {
	WixlWixElement parent_instance;
	WixlWixProductPrivate * priv;
};

struct _WixlWixProductClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixMedia {
	WixlWixElement parent_instance;
	WixlWixMediaPrivate * priv;
	LibmsiRecord* record;
};

struct _WixlWixMediaClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixRegistryKey {
	WixlWixElement parent_instance;
	WixlWixRegistryKeyPrivate * priv;
};

struct _WixlWixRegistryKeyClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixComponent {
	WixlWixElement parent_instance;
	WixlWixComponentPrivate * priv;
	WixlWixKeyElement* key;
	GList* in_feature;
};

struct _WixlWixComponentClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixDirectory {
	WixlWixElement parent_instance;
	WixlWixDirectoryPrivate * priv;
};

struct _WixlWixDirectoryClass {
	WixlWixElementClass parent_class;
};

struct _WixlWixDirectoryRef {
	WixlWixElementRef parent_instance;
	WixlWixDirectoryRefPrivate * priv;
};

struct _WixlWixDirectoryRefClass {
	WixlWixElementRefClass parent_class;
};


gpointer wixl_msi_default_ref (gpointer instance);
void wixl_msi_default_unref (gpointer instance);
GParamSpec* wixl_param_spec_msi_default (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void wixl_value_set_msi_default (GValue* value, gpointer v_object);
void wixl_value_take_msi_default (GValue* value, gpointer v_object);
gpointer wixl_value_get_msi_default (const GValue* value);
GType wixl_msi_default_get_type (void) G_GNUC_CONST;
GType wixl_msi_default_action_flags_get_type (void) G_GNUC_CONST;
GType wixl_msi_default_action_get_type (void) G_GNUC_CONST;
GType wixl_msi_default_action_info_get_type (void) G_GNUC_CONST;
WixlMSIDefaultActionInfo* wixl_msi_default_action_info_dup (const WixlMSIDefaultActionInfo* self);
void wixl_msi_default_action_info_free (WixlMSIDefaultActionInfo* self);
void wixl_msi_default_action_info_copy (const WixlMSIDefaultActionInfo* self, WixlMSIDefaultActionInfo* dest);
void wixl_msi_default_action_info_destroy (WixlMSIDefaultActionInfo* self);
void wixl_msi_default_get_action (WixlMSIDefaultAction action, WixlMSIDefaultActionInfo* result);
WixlMSIDefaultActionInfo* wixl_msi_default_get_action_by_name (const gchar* name);
WixlMSIDefault* wixl_msi_default_new (void);
WixlMSIDefault* wixl_msi_default_construct (GType object_type);
GType wixl_msi_table_get_type (void) G_GNUC_CONST;
void wixl_msi_table_create (WixlMsiTable* self, LibmsiDatabase* db, GError** error);
WixlMsiTable* wixl_msi_table_construct (GType object_type);
GType wixl_msi_table_sequence_get_type (void) G_GNUC_CONST;
void wixl_msi_table_sequence_set_sequence_table_name (WixlMsiTableSequenceClass* klass, const gchar* table);
void wixl_msi_table_sequence_add_sorted_actions (WixlMsiTableSequence* self, GError** error);
gpointer wixl_msi_table_sequence_action_ref (gpointer instance);
void wixl_msi_table_sequence_action_unref (gpointer instance);
GParamSpec* wixl_msi_table_sequence_param_spec_action (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void wixl_msi_table_sequence_value_set_action (GValue* value, gpointer v_object);
void wixl_msi_table_sequence_value_take_action (GValue* value, gpointer v_object);
gpointer wixl_msi_table_sequence_value_get_action (const GValue* value);
GType wixl_msi_table_sequence_action_get_type (void) G_GNUC_CONST;
WixlMsiTableSequenceAction* wixl_msi_table_sequence_get_action (WixlMsiTableSequence* self, const gchar* name);
void wixl_msi_table_sequence_add_default_action (WixlMsiTableSequence* self, WixlMSIDefaultAction action);
WixlMsiTableSequence* wixl_msi_table_sequence_construct (GType object_type);
GType wixl_wix_node_get_type (void) G_GNUC_CONST;
GType wixl_wix_element_get_type (void) G_GNUC_CONST;
GType wixl_wix_action_get_type (void) G_GNUC_CONST;
void wixl_msi_table_sequence_action_add_dep (WixlMsiTableSequenceAction* self, WixlMsiTableSequenceAction* a);
WixlMsiTableSequenceAction* wixl_msi_table_sequence_action_new (void);
WixlMsiTableSequenceAction* wixl_msi_table_sequence_action_construct (GType object_type);
GType wixl_wix_resolver_get_type (void) G_GNUC_CONST;
gpointer wixl_wix_resolver_find_element (WixlWixResolver* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, const gchar* Id);
gpointer wixl_wix_resolver_resolve (WixlWixResolver* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, WixlWixElement* element, GError** error);
GType wixl_visit_state_get_type (void) G_GNUC_CONST;
GType wixl_wix_node_visitor_get_type (void) G_GNUC_CONST;
GType wixl_wix_product_get_type (void) G_GNUC_CONST;
GType wixl_wix_icon_get_type (void) G_GNUC_CONST;
GType wixl_wix_package_get_type (void) G_GNUC_CONST;
GType wixl_wix_property_get_type (void) G_GNUC_CONST;
GType wixl_wix_media_get_type (void) G_GNUC_CONST;
GType wixl_wix_directory_get_type (void) G_GNUC_CONST;
GType wixl_wix_component_get_type (void) G_GNUC_CONST;
GType wixl_wix_feature_get_type (void) G_GNUC_CONST;
GType wixl_wix_element_ref_get_type (void) G_GNUC_CONST;
GType wixl_wix_component_ref_get_type (void) G_GNUC_CONST;
GType wixl_wix_remove_folder_get_type (void) G_GNUC_CONST;
GType wixl_wix_key_element_get_type (void) G_GNUC_CONST;
GType wixl_wix_registry_value_get_type (void) G_GNUC_CONST;
GType wixl_wix_file_get_type (void) G_GNUC_CONST;
GType wixl_wix_shortcut_get_type (void) G_GNUC_CONST;
GType wixl_wix_create_folder_get_type (void) G_GNUC_CONST;
GType wixl_wix_fragment_get_type (void) G_GNUC_CONST;
GType wixl_wix_sequence_get_type (void) G_GNUC_CONST;
GType wixl_wix_condition_get_type (void) G_GNUC_CONST;
GType wixl_wix_upgrade_get_type (void) G_GNUC_CONST;
GType wixl_wix_upgrade_version_get_type (void) G_GNUC_CONST;
GType wixl_wix_text_get_type (void) G_GNUC_CONST;
GType wixl_wix_component_group_ref_get_type (void) G_GNUC_CONST;
GType wixl_wix_prog_id_get_type (void) G_GNUC_CONST;
GType wixl_wix_extension_get_type (void) G_GNUC_CONST;
GType wixl_wix_verb_get_type (void) G_GNUC_CONST;
GType wixl_wix_mime_get_type (void) G_GNUC_CONST;
GType wixl_wix_service_argument_get_type (void) G_GNUC_CONST;
GType wixl_wix_service_control_get_type (void) G_GNUC_CONST;
GType wixl_wix_service_dependency_get_type (void) G_GNUC_CONST;
GType wixl_wix_service_install_get_type (void) G_GNUC_CONST;
GType wixl_wix_registry_search_get_type (void) G_GNUC_CONST;
GType wixl_wix_custom_action_get_type (void) G_GNUC_CONST;
GType wixl_wix_binary_get_type (void) G_GNUC_CONST;
GType wixl_wix_major_upgrade_get_type (void) G_GNUC_CONST;
GType wixl_wix_media_template_get_type (void) G_GNUC_CONST;
void wixl_wix_node_visitor_visit_product (WixlWixNodeVisitor* self, WixlWixProduct* product, GError** error);
void wixl_wix_node_visitor_visit_icon (WixlWixNodeVisitor* self, WixlWixIcon* icon, GError** error);
void wixl_wix_node_visitor_visit_package (WixlWixNodeVisitor* self, WixlWixPackage* package, GError** error);
void wixl_wix_node_visitor_visit_property (WixlWixNodeVisitor* self, WixlWixProperty* prop, GError** error);
void wixl_wix_node_visitor_visit_media (WixlWixNodeVisitor* self, WixlWixMedia* media, GError** error);
void wixl_wix_node_visitor_visit_directory (WixlWixNodeVisitor* self, WixlWixDirectory* dir, GError** error);
void wixl_wix_node_visitor_visit_component (WixlWixNodeVisitor* self, WixlWixComponent* comp, WixlVisitState state, GError** error);
void wixl_wix_node_visitor_visit_feature (WixlWixNodeVisitor* self, WixlWixFeature* feature, WixlVisitState state, GError** error);
void wixl_wix_node_visitor_visit_component_ref (WixlWixNodeVisitor* self, WixlWixComponentRef* ref, GError** error);
void wixl_wix_node_visitor_visit_remove_folder (WixlWixNodeVisitor* self, WixlWixRemoveFolder* rm, GError** error);
void wixl_wix_node_visitor_visit_registry_value (WixlWixNodeVisitor* self, WixlWixRegistryValue* reg, GError** error);
void wixl_wix_node_visitor_visit_file (WixlWixNodeVisitor* self, WixlWixFile* reg, GError** error);
void wixl_wix_node_visitor_visit_shortcut (WixlWixNodeVisitor* self, WixlWixShortcut* shortcut, GError** error);
void wixl_wix_node_visitor_visit_create_folder (WixlWixNodeVisitor* self, WixlWixCreateFolder* folder, GError** error);
void wixl_wix_node_visitor_visit_fragment (WixlWixNodeVisitor* self, WixlWixFragment* fragment, GError** error);
void wixl_wix_node_visitor_visit_sequence (WixlWixNodeVisitor* self, WixlWixSequence* sequence, GError** error);
void wixl_wix_node_visitor_visit_condition (WixlWixNodeVisitor* self, WixlWixCondition* condition, GError** error);
void wixl_wix_node_visitor_visit_upgrade (WixlWixNodeVisitor* self, WixlWixUpgrade* upgrade, GError** error);
void wixl_wix_node_visitor_visit_upgrade_version (WixlWixNodeVisitor* self, WixlWixUpgradeVersion* version, GError** error);
void wixl_wix_node_visitor_visit_action (WixlWixNodeVisitor* self, WixlWixAction* action, GError** error);
void wixl_wix_node_visitor_visit_text (WixlWixNodeVisitor* self, WixlWixText* text, GError** error);
void wixl_wix_node_visitor_visit_component_group_ref (WixlWixNodeVisitor* self, WixlWixComponentGroupRef* ref, GError** error);
void wixl_wix_node_visitor_visit_progid (WixlWixNodeVisitor* self, WixlWixProgId* progid, GError** error);
void wixl_wix_node_visitor_visit_extension (WixlWixNodeVisitor* self, WixlWixExtension* extension, GError** error);
void wixl_wix_node_visitor_visit_verb (WixlWixNodeVisitor* self, WixlWixVerb* verb, GError** error);
void wixl_wix_node_visitor_visit_mime (WixlWixNodeVisitor* self, WixlWixMIME* mime, GError** error);
void wixl_wix_node_visitor_visit_service_argument (WixlWixNodeVisitor* self, WixlWixServiceArgument* service_argument, GError** error);
void wixl_wix_node_visitor_visit_service_control (WixlWixNodeVisitor* self, WixlWixServiceControl* service_control, WixlVisitState state, GError** error);
void wixl_wix_node_visitor_visit_service_dependency (WixlWixNodeVisitor* self, WixlWixServiceDependency* service_dependency, GError** error);
void wixl_wix_node_visitor_visit_service_install (WixlWixNodeVisitor* self, WixlWixServiceInstall* service_install, WixlVisitState state, GError** error);
void wixl_wix_node_visitor_visit_registry_search (WixlWixNodeVisitor* self, WixlWixRegistrySearch* search, GError** error);
void wixl_wix_node_visitor_visit_custom_action (WixlWixNodeVisitor* self, WixlWixCustomAction* action, GError** error);
void wixl_wix_node_visitor_visit_binary (WixlWixNodeVisitor* self, WixlWixBinary* binary, GError** error);
void wixl_wix_node_visitor_visit_major_upgrade (WixlWixNodeVisitor* self, WixlWixMajorUpgrade* major, GError** error);
void wixl_wix_node_visitor_visit_media_template (WixlWixNodeVisitor* self, WixlWixMediaTemplate* media, GError** error);
WixlWixNodeVisitor* wixl_wix_node_visitor_construct (GType object_type);
gchar* wixl_wix_node_to_string (WixlWixNode* self);
void wixl_wix_node_value_to_string (GValue* src, GValue* dest);
WixlWixNode* wixl_wix_node_value_get_node (GValue* value);
void wixl_wix_node_accept (WixlWixNode* self, WixlWixNodeVisitor* visitor, GError** error);
WixlWixNode* wixl_wix_node_construct (GType object_type);
WixlWixText* wixl_wix_text_new (const gchar* str);
WixlWixText* wixl_wix_text_construct (GType object_type, const gchar* str);
void wixl_wix_element_add_child_types (WixlWixElementClass* klass, GHashTable* table, GType* child_types, int child_types_length1);
void wixl_wix_element_add_child (WixlWixElement* self, WixlWixNode* e);
gpointer* wixl_wix_element_add_elements (WixlWixElement* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, gpointer* a, int a_length1, int* result_length1);
gchar* wixl_wix_element_full_path (WixlWixElement* self, WixlWixResolver* r, GError** error);
gpointer* wixl_wix_element_get_elements (WixlWixElement* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, int* result_length1);
gpointer wixl_wix_element_find_element (WixlWixElement* self, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, const gchar* Id);
void wixl_wix_element_load_properties_from_node (WixlWixElement* self, xmlNode* node, GError** error);
void wixl_wix_element_load (WixlWixElement* self, xmlNode* node, GError** error);
WixlWixElement* wixl_wix_element_construct (GType object_type);
const gchar* wixl_wix_element_get_Id (WixlWixElement* self);
void wixl_wix_element_set_Id (WixlWixElement* self, const gchar* value);
GType wixl_wix_component_group_get_type (void) G_GNUC_CONST;
WixlWixComponentGroup* wixl_wix_component_group_new (void);
WixlWixComponentGroup* wixl_wix_component_group_construct (GType object_type);
const gchar* wixl_wix_component_group_get_Directory (WixlWixComponentGroup* self);
void wixl_wix_component_group_set_Directory (WixlWixComponentGroup* self, const gchar* value);
WixlWixFragment* wixl_wix_fragment_new (void);
WixlWixFragment* wixl_wix_fragment_construct (GType object_type);
WixlWixRegistrySearch* wixl_wix_registry_search_new (void);
WixlWixRegistrySearch* wixl_wix_registry_search_construct (GType object_type);
const gchar* wixl_wix_registry_search_get_Root (WixlWixRegistrySearch* self);
void wixl_wix_registry_search_set_Root (WixlWixRegistrySearch* self, const gchar* value);
const gchar* wixl_wix_registry_search_get_Key (WixlWixRegistrySearch* self);
void wixl_wix_registry_search_set_Key (WixlWixRegistrySearch* self, const gchar* value);
const gchar* wixl_wix_registry_search_get_Type (WixlWixRegistrySearch* self);
void wixl_wix_registry_search_set_Type (WixlWixRegistrySearch* self, const gchar* value);
const gchar* wixl_wix_registry_search_get_Name (WixlWixRegistrySearch* self);
void wixl_wix_registry_search_set_Name (WixlWixRegistrySearch* self, const gchar* value);
const gchar* wixl_wix_registry_search_get_Win64 (WixlWixRegistrySearch* self);
void wixl_wix_registry_search_set_Win64 (WixlWixRegistrySearch* self, const gchar* value);
WixlWixProperty* wixl_wix_property_new (void);
WixlWixProperty* wixl_wix_property_construct (GType object_type);
const gchar* wixl_wix_property_get_Value (WixlWixProperty* self);
void wixl_wix_property_set_Value (WixlWixProperty* self, const gchar* value);
WixlWixPackage* wixl_wix_package_new (void);
WixlWixPackage* wixl_wix_package_construct (GType object_type);
const gchar* wixl_wix_package_get_Keywords (WixlWixPackage* self);
void wixl_wix_package_set_Keywords (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_InstallerDescription (WixlWixPackage* self);
void wixl_wix_package_set_InstallerDescription (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_InstallerComments (WixlWixPackage* self);
void wixl_wix_package_set_InstallerComments (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_Manufacturer (WixlWixPackage* self);
void wixl_wix_package_set_Manufacturer (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_InstallerVersion (WixlWixPackage* self);
void wixl_wix_package_set_InstallerVersion (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_Languages (WixlWixPackage* self);
void wixl_wix_package_set_Languages (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_Compressed (WixlWixPackage* self);
void wixl_wix_package_set_Compressed (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_SummaryCodepage (WixlWixPackage* self);
void wixl_wix_package_set_SummaryCodepage (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_Comments (WixlWixPackage* self);
void wixl_wix_package_set_Comments (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_Description (WixlWixPackage* self);
void wixl_wix_package_set_Description (WixlWixPackage* self, const gchar* value);
const gchar* wixl_wix_package_get_InstallScope (WixlWixPackage* self);
void wixl_wix_package_set_InstallScope (WixlWixPackage* self, const gchar* value);
WixlWixCreateFolder* wixl_wix_create_folder_new (void);
WixlWixCreateFolder* wixl_wix_create_folder_construct (GType object_type);
const gchar* wixl_wix_create_folder_get_Directory (WixlWixCreateFolder* self);
void wixl_wix_create_folder_set_Directory (WixlWixCreateFolder* self, const gchar* value);
WixlWixIcon* wixl_wix_icon_new (void);
WixlWixIcon* wixl_wix_icon_construct (GType object_type);
const gchar* wixl_wix_icon_get_SourceFile (WixlWixIcon* self);
void wixl_wix_icon_set_SourceFile (WixlWixIcon* self, const gchar* value);
WixlWixComponent* wixl_wix_shortcut_get_component (WixlWixShortcut* self);
WixlWixShortcut* wixl_wix_shortcut_new (void);
WixlWixShortcut* wixl_wix_shortcut_construct (GType object_type);
const gchar* wixl_wix_shortcut_get_Directory (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Directory (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_Name (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Name (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_IconIndex (WixlWixShortcut* self);
void wixl_wix_shortcut_set_IconIndex (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_WorkingDirectory (WixlWixShortcut* self);
void wixl_wix_shortcut_set_WorkingDirectory (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_Icon (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Icon (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_Advertise (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Advertise (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_Description (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Description (WixlWixShortcut* self, const gchar* value);
const gchar* wixl_wix_shortcut_get_Target (WixlWixShortcut* self);
void wixl_wix_shortcut_set_Target (WixlWixShortcut* self, const gchar* value);
gchar* wixl_wix_key_element_path_name (WixlWixKeyElement* self, GError** error);
WixlWixKeyElement* wixl_wix_key_element_construct (GType object_type);
const gchar* wixl_wix_key_element_get_KeyPath (WixlWixKeyElement* self);
void wixl_wix_key_element_set_KeyPath (WixlWixKeyElement* self, const gchar* value);
WixlWixFile* wixl_wix_file_new (void);
WixlWixFile* wixl_wix_file_construct (GType object_type);
const gchar* wixl_wix_file_get_DiskId (WixlWixFile* self);
void wixl_wix_file_set_DiskId (WixlWixFile* self, const gchar* value);
const gchar* wixl_wix_file_get_Source (WixlWixFile* self);
void wixl_wix_file_set_Source (WixlWixFile* self, const gchar* value);
const gchar* wixl_wix_file_get_Name (WixlWixFile* self);
void wixl_wix_file_set_Name (WixlWixFile* self, const gchar* value);
WixlWixRegistryValue* wixl_wix_registry_value_new (void);
WixlWixRegistryValue* wixl_wix_registry_value_construct (GType object_type);
const gchar* wixl_wix_registry_value_get_Root (WixlWixRegistryValue* self);
void wixl_wix_registry_value_set_Root (WixlWixRegistryValue* self, const gchar* value);
const gchar* wixl_wix_registry_value_get_Key (WixlWixRegistryValue* self);
void wixl_wix_registry_value_set_Key (WixlWixRegistryValue* self, const gchar* value);
const gchar* wixl_wix_registry_value_get_Type (WixlWixRegistryValue* self);
void wixl_wix_registry_value_set_Type (WixlWixRegistryValue* self, const gchar* value);
const gchar* wixl_wix_registry_value_get_Value (WixlWixRegistryValue* self);
void wixl_wix_registry_value_set_Value (WixlWixRegistryValue* self, const gchar* value);
const gchar* wixl_wix_registry_value_get_Name (WixlWixRegistryValue* self);
void wixl_wix_registry_value_set_Name (WixlWixRegistryValue* self, const gchar* value);
WixlWixRemoveFolder* wixl_wix_remove_folder_new (void);
WixlWixRemoveFolder* wixl_wix_remove_folder_construct (GType object_type);
const gchar* wixl_wix_remove_folder_get_On (WixlWixRemoveFolder* self);
void wixl_wix_remove_folder_set_On (WixlWixRemoveFolder* self, const gchar* value);
WixlWixFeature* wixl_wix_feature_new (void);
WixlWixFeature* wixl_wix_feature_construct (GType object_type);
const gchar* wixl_wix_feature_get_Level (WixlWixFeature* self);
void wixl_wix_feature_set_Level (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_Title (WixlWixFeature* self);
void wixl_wix_feature_set_Title (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_Description (WixlWixFeature* self);
void wixl_wix_feature_set_Description (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_Display (WixlWixFeature* self);
void wixl_wix_feature_set_Display (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_ConfigurableDirectory (WixlWixFeature* self);
void wixl_wix_feature_set_ConfigurableDirectory (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_AllowAdvertise (WixlWixFeature* self);
void wixl_wix_feature_set_AllowAdvertise (WixlWixFeature* self, const gchar* value);
const gchar* wixl_wix_feature_get_Absent (WixlWixFeature* self);
void wixl_wix_feature_set_Absent (WixlWixFeature* self, const gchar* value);
WixlWixComponentRef* wixl_wix_component_ref_new (void);
WixlWixComponentRef* wixl_wix_component_ref_construct (GType object_type);
WixlWixComponentGroupRef* wixl_wix_component_group_ref_new (void);
WixlWixComponentGroupRef* wixl_wix_component_group_ref_construct (GType object_type);
WixlWixCondition* wixl_wix_condition_new (void);
WixlWixCondition* wixl_wix_condition_construct (GType object_type);
const gchar* wixl_wix_condition_get_Message (WixlWixCondition* self);
void wixl_wix_condition_set_Message (WixlWixCondition* self, const gchar* value);
WixlWixMIME* wixl_wix_mime_new (void);
WixlWixMIME* wixl_wix_mime_construct (GType object_type);
const gchar* wixl_wix_mime_get_Advertise (WixlWixMIME* self);
void wixl_wix_mime_set_Advertise (WixlWixMIME* self, const gchar* value);
const gchar* wixl_wix_mime_get_ContentType (WixlWixMIME* self);
void wixl_wix_mime_set_ContentType (WixlWixMIME* self, const gchar* value);
const gchar* wixl_wix_mime_get_Default (WixlWixMIME* self);
void wixl_wix_mime_set_Default (WixlWixMIME* self, const gchar* value);
gchar* wixl_wix_service_argument_get_text (WixlWixServiceArgument* self);
WixlWixServiceArgument* wixl_wix_service_argument_new (void);
WixlWixServiceArgument* wixl_wix_service_argument_construct (GType object_type);
WixlWixServiceControl* wixl_wix_service_control_new (void);
WixlWixServiceControl* wixl_wix_service_control_construct (GType object_type);
const gchar* wixl_wix_service_control_get_Name (WixlWixServiceControl* self);
void wixl_wix_service_control_set_Name (WixlWixServiceControl* self, const gchar* value);
const gchar* wixl_wix_service_control_get_Start (WixlWixServiceControl* self);
void wixl_wix_service_control_set_Start (WixlWixServiceControl* self, const gchar* value);
const gchar* wixl_wix_service_control_get_Stop (WixlWixServiceControl* self);
void wixl_wix_service_control_set_Stop (WixlWixServiceControl* self, const gchar* value);
const gchar* wixl_wix_service_control_get_Remove (WixlWixServiceControl* self);
void wixl_wix_service_control_set_Remove (WixlWixServiceControl* self, const gchar* value);
const gchar* wixl_wix_service_control_get_Wait (WixlWixServiceControl* self);
void wixl_wix_service_control_set_Wait (WixlWixServiceControl* self, const gchar* value);
WixlWixServiceDependency* wixl_wix_service_dependency_new (void);
WixlWixServiceDependency* wixl_wix_service_dependency_construct (GType object_type);
const gchar* wixl_wix_service_dependency_get_Group (WixlWixServiceDependency* self);
void wixl_wix_service_dependency_set_Group (WixlWixServiceDependency* self, const gchar* value);
WixlWixServiceInstall* wixl_wix_service_install_new (void);
WixlWixServiceInstall* wixl_wix_service_install_construct (GType object_type);
const gchar* wixl_wix_service_install_get_Name (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Name (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_DisplayName (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_DisplayName (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Type (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Type (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Interactive (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Interactive (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Start (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Start (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_ErrorControl (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_ErrorControl (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Vital (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Vital (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_LoadOrderGroup (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_LoadOrderGroup (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Account (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Account (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Password (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Password (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Arguments (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Arguments (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_Description (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_Description (WixlWixServiceInstall* self, const gchar* value);
const gchar* wixl_wix_service_install_get_EraseDescription (WixlWixServiceInstall* self);
void wixl_wix_service_install_set_EraseDescription (WixlWixServiceInstall* self, const gchar* value);
WixlWixVerb* wixl_wix_verb_new (void);
WixlWixVerb* wixl_wix_verb_construct (GType object_type);
const gchar* wixl_wix_verb_get_Command (WixlWixVerb* self);
void wixl_wix_verb_set_Command (WixlWixVerb* self, const gchar* value);
const gchar* wixl_wix_verb_get_TargetFile (WixlWixVerb* self);
void wixl_wix_verb_set_TargetFile (WixlWixVerb* self, const gchar* value);
const gchar* wixl_wix_verb_get_Argument (WixlWixVerb* self);
void wixl_wix_verb_set_Argument (WixlWixVerb* self, const gchar* value);
WixlWixExtension* wixl_wix_extension_new (void);
WixlWixExtension* wixl_wix_extension_construct (GType object_type);
const gchar* wixl_wix_extension_get_ContentType (WixlWixExtension* self);
void wixl_wix_extension_set_ContentType (WixlWixExtension* self, const gchar* value);
const gchar* wixl_wix_extension_get_Advertise (WixlWixExtension* self);
void wixl_wix_extension_set_Advertise (WixlWixExtension* self, const gchar* value);
WixlWixProgId* wixl_wix_prog_id_new (void);
WixlWixProgId* wixl_wix_prog_id_construct (GType object_type);
const gchar* wixl_wix_prog_id_get_Description (WixlWixProgId* self);
void wixl_wix_prog_id_set_Description (WixlWixProgId* self, const gchar* value);
const gchar* wixl_wix_prog_id_get_Advertise (WixlWixProgId* self);
void wixl_wix_prog_id_set_Advertise (WixlWixProgId* self, const gchar* value);
WixlWixAction* wixl_wix_action_new (void);
WixlWixAction* wixl_wix_action_construct (GType object_type);
const gchar* wixl_wix_action_get_After (WixlWixAction* self);
void wixl_wix_action_set_After (WixlWixAction* self, const gchar* value);
const gchar* wixl_wix_action_get_Before (WixlWixAction* self);
void wixl_wix_action_set_Before (WixlWixAction* self, const gchar* value);
const gchar* wixl_wix_action_get_Overridable (WixlWixAction* self);
void wixl_wix_action_set_Overridable (WixlWixAction* self, const gchar* value);
const gchar* wixl_wix_action_get_Sequence (WixlWixAction* self);
void wixl_wix_action_set_Sequence (WixlWixAction* self, const gchar* value);
const gchar* wixl_wix_action_get_Suppress (WixlWixAction* self);
void wixl_wix_action_set_Suppress (WixlWixAction* self, const gchar* value);
const gchar* wixl_wix_action_get_Action (WixlWixAction* self);
void wixl_wix_action_set_Action (WixlWixAction* self, const gchar* value);
WixlWixSequence* wixl_wix_sequence_new (void);
WixlWixSequence* wixl_wix_sequence_construct (GType object_type);
GType wixl_wix_install_execute_sequence_get_type (void) G_GNUC_CONST;
WixlWixInstallExecuteSequence* wixl_wix_install_execute_sequence_new (void);
WixlWixInstallExecuteSequence* wixl_wix_install_execute_sequence_construct (GType object_type);
GType wixl_wix_install_ui_sequence_get_type (void) G_GNUC_CONST;
WixlWixInstallUISequence* wixl_wix_install_ui_sequence_new (void);
WixlWixInstallUISequence* wixl_wix_install_ui_sequence_construct (GType object_type);
GType wixl_wix_admin_execute_sequence_get_type (void) G_GNUC_CONST;
WixlWixAdminExecuteSequence* wixl_wix_admin_execute_sequence_new (void);
WixlWixAdminExecuteSequence* wixl_wix_admin_execute_sequence_construct (GType object_type);
GType wixl_wix_admin_ui_sequence_get_type (void) G_GNUC_CONST;
WixlWixAdminUISequence* wixl_wix_admin_ui_sequence_new (void);
WixlWixAdminUISequence* wixl_wix_admin_ui_sequence_construct (GType object_type);
GType wixl_wix_advertise_execute_sequence_get_type (void) G_GNUC_CONST;
WixlWixAdvertiseExecuteSequence* wixl_wix_advertise_execute_sequence_new (void);
WixlWixAdvertiseExecuteSequence* wixl_wix_advertise_execute_sequence_construct (GType object_type);
WixlWixUpgrade* wixl_wix_upgrade_new (void);
WixlWixUpgrade* wixl_wix_upgrade_construct (GType object_type);
WixlWixUpgradeVersion* wixl_wix_upgrade_version_new (void);
WixlWixUpgradeVersion* wixl_wix_upgrade_version_construct (GType object_type);
const gchar* wixl_wix_upgrade_version_get_Minimum (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_Minimum (WixlWixUpgradeVersion* self, const gchar* value);
const gchar* wixl_wix_upgrade_version_get_Maximum (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_Maximum (WixlWixUpgradeVersion* self, const gchar* value);
const gchar* wixl_wix_upgrade_version_get_IncludeMinimum (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_IncludeMinimum (WixlWixUpgradeVersion* self, const gchar* value);
const gchar* wixl_wix_upgrade_version_get_IncludeMaximum (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_IncludeMaximum (WixlWixUpgradeVersion* self, const gchar* value);
const gchar* wixl_wix_upgrade_version_get_OnlyDetect (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_OnlyDetect (WixlWixUpgradeVersion* self, const gchar* value);
const gchar* wixl_wix_upgrade_version_get_Property (WixlWixUpgradeVersion* self);
void wixl_wix_upgrade_version_set_Property (WixlWixUpgradeVersion* self, const gchar* value);
WixlWixCustomAction* wixl_wix_custom_action_new (void);
WixlWixCustomAction* wixl_wix_custom_action_construct (GType object_type);
const gchar* wixl_wix_custom_action_get_Property (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_Property (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_Execute (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_Execute (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_ExeCommand (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_ExeCommand (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_Impersonate (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_Impersonate (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_Return (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_Return (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_BinaryKey (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_BinaryKey (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_DllEntry (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_DllEntry (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_HideTarget (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_HideTarget (WixlWixCustomAction* self, const gchar* value);
const gchar* wixl_wix_custom_action_get_JScriptCall (WixlWixCustomAction* self);
void wixl_wix_custom_action_set_JScriptCall (WixlWixCustomAction* self, const gchar* value);
WixlWixBinary* wixl_wix_binary_new (void);
WixlWixBinary* wixl_wix_binary_construct (GType object_type);
const gchar* wixl_wix_binary_get_SourceFile (WixlWixBinary* self);
void wixl_wix_binary_set_SourceFile (WixlWixBinary* self, const gchar* value);
WixlWixMajorUpgrade* wixl_wix_major_upgrade_new (void);
WixlWixMajorUpgrade* wixl_wix_major_upgrade_construct (GType object_type);
const gchar* wixl_wix_major_upgrade_get_DowngradeErrorMessage (WixlWixMajorUpgrade* self);
void wixl_wix_major_upgrade_set_DowngradeErrorMessage (WixlWixMajorUpgrade* self, const gchar* value);
WixlWixMediaTemplate* wixl_wix_media_template_new (void);
WixlWixMediaTemplate* wixl_wix_media_template_construct (GType object_type);
const gchar* wixl_wix_media_template_get_EmbedCab (WixlWixMediaTemplate* self);
void wixl_wix_media_template_set_EmbedCab (WixlWixMediaTemplate* self, const gchar* value);
WixlWixProduct* wixl_wix_product_new (void);
WixlWixProduct* wixl_wix_product_construct (GType object_type);
const gchar* wixl_wix_product_get_Name (WixlWixProduct* self);
void wixl_wix_product_set_Name (WixlWixProduct* self, const gchar* value);
const gchar* wixl_wix_product_get_UpgradeCode (WixlWixProduct* self);
void wixl_wix_product_set_UpgradeCode (WixlWixProduct* self, const gchar* value);
const gchar* wixl_wix_product_get_Language (WixlWixProduct* self);
void wixl_wix_product_set_Language (WixlWixProduct* self, const gchar* value);
const gchar* wixl_wix_product_get_Codepage (WixlWixProduct* self);
void wixl_wix_product_set_Codepage (WixlWixProduct* self, const gchar* value);
const gchar* wixl_wix_product_get_Version (WixlWixProduct* self);
void wixl_wix_product_set_Version (WixlWixProduct* self, const gchar* value);
const gchar* wixl_wix_product_get_Manufacturer (WixlWixProduct* self);
void wixl_wix_product_set_Manufacturer (WixlWixProduct* self, const gchar* value);
WixlWixMedia* wixl_wix_media_new (void);
WixlWixMedia* wixl_wix_media_construct (GType object_type);
const gchar* wixl_wix_media_get_Cabinet (WixlWixMedia* self);
void wixl_wix_media_set_Cabinet (WixlWixMedia* self, const gchar* value);
const gchar* wixl_wix_media_get_EmbedCab (WixlWixMedia* self);
void wixl_wix_media_set_EmbedCab (WixlWixMedia* self, const gchar* value);
const gchar* wixl_wix_media_get_DiskPrompt (WixlWixMedia* self);
void wixl_wix_media_set_DiskPrompt (WixlWixMedia* self, const gchar* value);
GType wixl_wix_registry_key_get_type (void) G_GNUC_CONST;
WixlWixRegistryKey* wixl_wix_registry_key_new (void);
WixlWixRegistryKey* wixl_wix_registry_key_construct (GType object_type);
const gchar* wixl_wix_registry_key_get_Key (WixlWixRegistryKey* self);
void wixl_wix_registry_key_set_Key (WixlWixRegistryKey* self, const gchar* value);
const gchar* wixl_wix_registry_key_get_Root (WixlWixRegistryKey* self);
void wixl_wix_registry_key_set_Root (WixlWixRegistryKey* self, const gchar* value);
WixlWixComponent* wixl_wix_component_new (void);
WixlWixComponent* wixl_wix_component_construct (GType object_type);
const gchar* wixl_wix_component_get_Guid (WixlWixComponent* self);
void wixl_wix_component_set_Guid (WixlWixComponent* self, const gchar* value);
const gchar* wixl_wix_component_get_Win64 (WixlWixComponent* self);
void wixl_wix_component_set_Win64 (WixlWixComponent* self, const gchar* value);
WixlWixDirectory* wixl_wix_directory_new (void);
WixlWixDirectory* wixl_wix_directory_construct (GType object_type);
const gchar* wixl_wix_directory_get_Name (WixlWixDirectory* self);
void wixl_wix_directory_set_Name (WixlWixDirectory* self, const gchar* value);
WixlWixElementRef* wixl_wix_element_ref_new (GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func);
WixlWixElementRef* wixl_wix_element_ref_construct (GType object_type, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func);
GType wixl_wix_directory_ref_get_type (void) G_GNUC_CONST;
WixlWixDirectoryRef* wixl_wix_directory_ref_new (void);
WixlWixDirectoryRef* wixl_wix_directory_ref_construct (GType object_type);


G_END_DECLS

#endif
